"""Insight model for smart suggestions."""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any

from pydantic import BaseModel, Field
from pydantic.alias_generators import to_camel


class Insight(BaseModel):
    """A smart suggestion generated by the insights engine."""

    model_config = {"alias_generator": to_camel, "populate_by_name": True}

    id: str = Field(default_factory=lambda: uuid.uuid4().hex[:8])
    type: str = ""
    severity: str = "info"
    title: str = ""
    description: str = ""
    recommendation: str = ""
    tool_name: str | None = None
    data_points: dict[str, Any] = {}
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    dismissed: bool = False
